# 1. Official Node.js image as the base
FROM node:18-alpine

#1.5 Label for image organization purposes
LABEL Name=frontend Version=0.0.1

# 2. Set the directory inside the container for our code
WORKDIR /app

# 3. Copy package files first to cache dependencies
COPY package*.json ./
COPY index.js ./

# 4. Install the dependencies for your React app (currently no dependencies, but this is how to add them)
#RUN npm install

# 5. Copy the rest of your React source code
COPY . .

# 6. Open port 3000 for the browser to access
EXPOSE 3000

# 7. Start the server
#for a REACT server:
#CMD ["npm", "start"]

#for now:
CMD ["node", "index.js"]